# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 15:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.IntegerField()),
                ('label_one', models.CharField(max_length=30)),
                ('label_two', models.CharField(blank=True, max_length=30, null=True)),
                ('label_three', models.CharField(blank=True, max_length=30, null=True)),
                ('label_four', models.CharField(blank=True, max_length=30, null=True)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=10, max_digits=15), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('index_stimulus_shown', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_variable', models.CharField(max_length=30)),
                ('information_value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Site'),
        ),
        migrations.AddField(
            model_name='data',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Experiment'),
        ),
        migrations.AddField(
            model_name='data',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Site'),
        ),
    ]
