# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 21:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('index_stimulus_shown', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_variable', models.CharField(max_length=30)),
                ('information_value', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('labels_one', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None)),
                ('labels_two', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None)),
                ('labels_three', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None)),
                ('labels_four', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=10, max_digits=15), blank=True, null=True, size=None), blank=True, null=True, size=None)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.Site'),
        ),
    ]
