# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 16:04
from __future__ import unicode_literals
import numpy as np

from django.db import migrations



def bin_data(data, num_trials,num_time_steps, bin_size, step_size):
    starts = np.arange(0,num_time_steps, step_size)
    ends = starts+ bin_size
    not_overflowing = ends<=num_time_steps
    starts = starts[not_overflowing]
    ends = ends[not_overflowing]
    ends[len(ends)-1]=num_time_steps
    binned_data = [np.mean(data[:, starts[i]:ends[i]],1).tolist() for i in np.arange(len(starts))]
    return(binned_data)


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Site = apps.get_model("visualize", "Site")
    BinnedData = apps.get_model("visualize", "BinnedData")
    i=0
    for site in Site.objects.all():
        if i % 10 == 0:
            print('Reading site number: ' + str(i))
        i+=1
        np_site_data = np.array(site.data)
        [num_trials, num_time_steps] = np_site_data.shape
        BinnedData.objects.using(db_alias).bulk_create([
            BinnedData(
                site=site,
                bin_150_50= bin_data(np_site_data, num_trials,num_time_steps, 150, 50),
                bin_100_30= bin_data(np_site_data, num_trials,num_time_steps, 100, 30),
                bin_50_15=bin_data(np_site_data, num_trials,num_time_steps, 50, 15)
                )
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0003_binneddata'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
