# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 16:10
# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 16:06
from __future__ import unicode_literals
import environ
import numpy as np
from os import listdir
from scipy.io import loadmat

from django.db import migrations


WHICH_MIGRATION = 'third'


def col_to_str_row(array):
    return str(np.round([item[0] for item in array], 5))


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Experiment = apps.get_model("visualize", "Experiment")
    isik_experiment = Experiment.objects.filter(slug="isik_26")

    Site = apps.get_model("visualize", "Site")
    Data = apps.get_model("visualize", "Data")
    Metadata = apps.get_model("visualize", "Metadata")
    isik_data_directory = str(environ.Path().path('neural_exploration',
                                                  'visualize',
                                                  'migrations',
                                                  'isik_data',
                                                  WHICH_MIGRATION))
    for i, mat_file in enumerate(listdir(isik_data_directory)):
        if i % 50 == 0:
            print(i)
        mat_data = loadmat(isik_data_directory + '/' + mat_file)

        data = mat_data['raster_data']
        labels = mat_data['raster_labels'][0][0][0]
        metadata_variables = mat_data['raster_site_info'][0].dtype.names
        metadata_values = [
            val[0] if len(val) == 1 else col_to_str_row(val)
            for val in mat_data['raster_site_info'][0][0]
        ]

        metadata = zip(metadata_variables, metadata_values)
        site_slug = mat_file[7:12]
        isik_site = Site(slug=site_slug, experiment=isik_experiment)
        Site.objects.using(db_alias).bulk_create([isik_site])

        Metadata.objects.using(db_alias).bulk_create([
            Metadata(
                site=isik_site,
                information_variable=var,
                information_value=val) for (var, val) in metadata
        ])
        Data.objects.using(db_alias).bulk_create([
            Data(
                experiment=isik_experiment,
                site=isik_site,
                trial_number=trial_number,
                label_one=labels[trial_number],
                data=data[trial_number, :].tolist())
            for trial_number in range(data.shape[0])
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0003_load_isik_data_2'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
